version: "3.8"

services:
  app:
    image: omarzakaria10/guessing_game:latest
    container_name: node_app
    restart: always
    environment:
      - NODE_ENV=production
      - DATABASE=mongodb://mongodb:27017/game_scores
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    networks:
      - app_network
    command: npm test # Override the default command to run tests

  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - app_network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - app_network

volumes:
  mongo_data:

networks:
  app_network:
    driver: bridge
