version: "3.8"

services:
  app:
    build:
      context: .  # This specifies the current directory as the build context (where Dockerfile is located)
      dockerfile: Dockerfile
    container_name: node_app
    # restart: always
    environment:
      - NODE_ENV=production
      - DATABASE=mongodb://mongodb:27017/game_scores
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    networks:
      - app_network
    command: ["npm", "test"]

  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - app_network

volumes:
  mongo_data:

networks:
  app_network:
    driver: bridge
