# https://github.com/grafana/loki/blob/main/production/docker-compose.yaml
---
x-common-config: &common
  logging:
    driver: json-file
    options:
      tag: "{{.Name}}"
      max-size: "100m"
      max-file: "3"
  mem_limit: "512M"

services:
  mongodb:
    <<: *common
    image: mongo:latest
    container_name: mongodb
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - app_network
  app:
    <<: *common
    image: omarzakaria10/guessing_game:latest
    container_name: app
    restart: always
    environment:
      - NODE_ENV=production
      - DATABASE=mongodb://mongodb:27017/game_scores
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    networks:
      - app_network

  nginx:
    <<: *common
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - app_network

  loki:
    <<: *common
    image: grafana/loki:latest
    container_name: loki
    # ports:
    #   - "3100:3100"
    volumes:
      - ./config:/mnt/config
    command: -config.file=/mnt/config/loki-config.yaml
    networks:
      - app_network

  promtail:
    <<: *common
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers # Needed for container logs
      - /var/log:/var/log
      - ./config:/mnt/config
    command: -config.file=/mnt/config/promtail-config.yaml
    networks:
      - app_network

  grafana:
    <<: *common
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./provisioning:/etc/grafana/provisioning
    networks:
      - app_network

  prometheus:
    <<: *common
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./config:/mnt/config
    command: --config.file=/mnt/config/prometheus-config.yaml
    networks:
      - app_network

volumes:
  mongo_data:

networks:
  app_network:
    driver: bridge
