apiVersion: v1
kind: Secret
metadata:
  name: my-secret
  namespace: {{ .Values.namespace  }}
type: Opaque
data:
  {{- range .Files.Lines "config.env" }}
  {{- if . }}
  {{- $parts := regexSplit "=" . 2 }}
  {{- if eq (len $parts) 2 }}
  {{- $key := index $parts 0 }}
  {{- $value := index $parts 1 | b64enc }}
  {{ $key | quote }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
  {{- end }}
