name: Docker Compose Testing and Deployment

on:
  push:
    branches:
      - main
    tags:
      - "v*"
    paths:
      - "app.js"
      - "dockerfile"
      - "src/**"
      - "controllers/**"
      - "public/**"
      - "routes/**"
      - "util/**"
      - "views/**"
      - ".github/workflows/nodetest.yml"
      - "models/**"
      - "app.test.js"
      - "testing/**" # Ensure testing directory changes trigger the action

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Run Docker Compose for Testing
        working-directory: ./testing # Specify the testing directory
        run: |
          docker-compose up --build  # Start the testing services
          # docker-compose exec app npm test  # Run tests inside the app container
          docker-compose down  # Tear down the containers after testing

  build_and_push_docker:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: omarzakaria10
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            omarzakaria10/guessing_game:latest
            omarzakaria10/guessing_game:${{ env.TAG || 'latest' }}
